export interface AdmTblDat{
    _id: string,
    table_name: string,
    key_desc: string,
    key_1: string,
    data_1: string,
    data_2: string,
    data_3: string,
    data_4: string,
    data_5: string,
    data_6: string,
    created: string,
    updated: string,
    __v: string,
}