export const CREATE_ADM_TBL_DAT = "CREATE_ADM_TBL_DAT";
export const RETRIEVE_ADM_TBL_DATS = "RETRIEVE_ADM_TBL_DATS";
export const UPDATE_ADM_TBL_DAT = "UPDATE_ADM_TBL_DAT";
export const DELETE_ADM_TBL_DAT = "DELETE_ADM_TBL_DAT";
export const DELETE_ALL_ADM_TBL_DATS = "DELETE_ALL_ADM_TBL_DATS";